# This is my learning python course

We **are** learning ~~matlab~~ *python* using __jupyter__ notebooks


## Analysing patient data

In [1]:
import numpy as np

In [2]:
np.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [3]:
weight_kg = 55
print(weight_kg)

55


In [4]:
print('Weight in pounds', 2.2*weight_kg)

Weight in pounds 121.00000000000001


In [5]:
weight_lb = 2.2*weight_kg
print('Weight in pounds:', weight_lb, 'and in kg:', weight_kg)

Weight in pounds: 121.00000000000001 and in kg: 55


In [6]:
weight_kg = 100
print('Weight in pounds:', weight_lb, 'and in kg:', weight_kg)

Weight in pounds: 121.00000000000001 and in kg: 100


In [7]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [8]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [9]:
%whos

Variable    Type       Data/Info
--------------------------------
data        ndarray    60x40: 2400 elems, type `float64`, 19200 bytes
np          module     <module 'numpy' from '//a<...>kages/numpy/__init__.py'>
weight_kg   int        100
weight_lb   float      121.00000000000001


In [10]:
print(type(data))

<class 'numpy.ndarray'>


In [11]:
print(type(weight_kg))

<class 'int'>


In [12]:
print(data.dtype)

float64


In [13]:
print(data.size)

2400


In [14]:
print(data.shape)

(60, 40)


In [16]:
print('my first value in data:', data[0][0])

my first value in data: 0.0


In [18]:
print('my middle value in data:', data[30][20])

my middle value in data: 13.0


In [21]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [22]:
small = data[:3, 36:]
print(small)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
